version: '3'

services:
  mysql:
    image: mariadb
    volumes:
      - /Volumes/EXTMAC/Docker/wp/data/sql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: splintx
      MARIADB_DATABASE: wpdocker_db
      MARIADB_USER: wpdocker_admin
      MARIADB_PASSWORD: kubernetes
    restart: always

  wordpress:
    image: wordpress:php8.0-fpm-alpine
    volumes:
      - /Volumes/EXTMAC/Docker/wp/data/app:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpdocker_admin
      WORDPRESS_DB_PASSWORD: kubernetes
      WORDPRESS_DB_NAME: wpdocker_db
      WORDPRESS_TABLE_PREFIX: wpd_
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - /Volumes/EXTMAC/Docker/wp/data/nginx:/etc/nginx/conf.d
      - /Volumes/EXTMAC/Docker/wp/data/app:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress