version: '3'

services:
  mysql:
    image: mariadb
    volumes:
      - ${LOCAL_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}
    restart: always

  wordpress:
    image: wordpress:php8.0-fpm-alpine
    volumes:
      - ${LOCAL_PATH}/web:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: splintx
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_PREFIX}
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ${LOCAL_PATH}/nginx:/etc/nginx/conf.d
      - ${LOCAL_PATH}/web:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress